import 'source-map-support/register'; //This import must remain on the first line
//Rest of app the imports
import { INestApplication, RequestMethod, ValidationPipe } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { GlobalExceptionsFilter, morganMiddleware } from '@snap/src';
import compression from 'compression';
import cookieParser from 'cookie-parser';
import expressBasicAuth from 'express-basic-auth';
import helmet from 'helmet';
import { ClsService } from 'nestjs-cls';
import { AppModule } from './app.module';

function setupSwagger(app: INestApplication, configService: ConfigService) {
  const options = new DocumentBuilder()
    .setTitle('NestJS Seed')
    .setDescription('NestSeed For Indexnine Technologies')
    .setVersion('0.1.0')
    .addSecurity('BearerAuthorization', {
      type: 'apiKey',
      in: 'header',
      name: 'Authorization',
      description: "Access token format: 'Bearer <access-token>'",
    })
    .build();

  const document = SwaggerModule.createDocument(app, options);

  const authenticatedSwaggerUIUsers = configService.get('swagger.authUsers');
  const swaggerUIPath = configService.get('swagger.uiPath');
  //here /api-json is the default path of json generated by swagger
  app.use([swaggerUIPath, '/api-json'], expressBasicAuth({ challenge: true, users: authenticatedSwaggerUIUsers }));

  SwaggerModule.setup(swaggerUIPath, app, document);
}

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {});

  app.enableCors();
  app.use(helmet());
  const configService = app.get(ConfigService);

  app.setGlobalPrefix(configService.get('contextPath'), { exclude: [{ path: 'health', method: RequestMethod.GET }] });

  if (configService.get('swagger.isEnabled')) {
    setupSwagger(app, configService);
  }

  app.useGlobalPipes(new ValidationPipe());
  app.use(cookieParser());

  app.use(morganMiddleware(configService.get('morgan.format')));

  const requestContextService: ClsService = app.get(ClsService);

  app.useGlobalFilters(new GlobalExceptionsFilter(requestContextService));

  app.use(compression());

  await app.listen(configService.get('PORT'));
}

bootstrap().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('Error during app bootstrap:', err);
  process.exit(1);
});
